# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
# test     

name: Build and deploy Python app to Azure Web App - budgetjurko

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: create .env file
        run: |
          touch .env
          echo AZURE_CLIENT_ID =${{ secrets.AZURE_CLIENT_ID }} >> .env
          echo AZURE_CLIENT_SECRET =${{ secrets.AZURE_CLIENT_SECRET }} >> .env
          echo AZURE_TENANT_ID =${{ secrets.AZURE_TENANT_ID }} >> .env
          echo AZURE_VAULT_URL =${{ secrets.AZURE_VAULT_URL }} >> .env
          echo AZURE_STORAGE_URL =${{ secrets.AZURE_STORAGE_URL }} >> .env
          echo SECRET_VALUE_FOR_1D5C3AF7 =${{ secrets.SECRET_VALUE_FOR_1D5C3AF7 }} >> .env
          echo CLIENT_ID_C0889116 =${{ secrets.CLIENT_ID_C0889116 }} >> .env

      - name: Print secret
        run: |
          echo "The value of my secret is ${{ secrets.AZURE_CLIENT_ID }}"
          echo "The value of my secret is ${{ secrets.AZURE_CLIENT_SECRET }}"
          echo "The value of my secret is ${{ secrets.AZURE_TENANT_ID }}"
          echo "The value of my secret is ${{ secrets.AZURE_VAULT_URL }}"
          

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
      
       # - name: 'App with secreates'
       #   env:
       #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
       #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       #     AZURE_VAULT_URL: ${{ secrets.AZURE_VAULT_URL }}
       #   run: |
       #     echo "The value of my secret is ${{ secrets.AZURE_CLIENT_ID }}"
       #     echo "The value of my secret is ${{ secrets.AZURE_CLIENT_SECRET }}"
       #     echo "The value of my secret is ${{ secrets.AZURE_TENANT_ID }}"
       #     echo "The value of my secret is ${{ secrets.AZURE_VAULT_URL }}"
        
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.A_CLIENT_ID }}
          tenant-id: ${{ secrets.A_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Confirm Azure login
        run: az account show
      
      # - name: Login to Azure
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F8FA599ECCAC446EB03BFD0F3D30C74F }}
      #     tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC4E1FCD306D4738B7070C3D9D060650 }}
      #     subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D0C5EAAB33C84F51A7C8D6F77B76060C }}

      - name: Verify Web App exists
        run: |
          az webapp show --name budgetjurko --resource-group Resource_PJ

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'budgetjurko'
          slot-name: 'Production'

      # Set Azure Web App environment variables (application settings)
      # - name: Set environment variables in Azure Web App
      #   run: |
      #     az webapp config appsettings set --name budgetjurko --resource-group Resource_PJ --settings AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }} AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} AZURE_VAULT_URL=${{ secrets.AZURE_VAULT_URL }}
          
